### ISSUE TITLE
status=203/EXEC

### ISSUE THREAD

**Issue by jkim-ridgit** [CrowdStrike/HEC-Log-Shipper#7]
I can't seem to get the service to run. I keep running into code=exited, status=203/EXEC.

**Comment by jshcodes** [comment]
Hi @jkim-ridgit -

I believe the .service needs to be updated, we're looking into this now.

**Comment by jkim-ridgit** [comment]
Oh shoot, I forgot to update the issue. It worked when I added a shebang at the top to use python3 and chmod +x the file. Not sure if there’s a prettier way to do it, but I was running Centos 7.9.

Thank you,
Joshua
_________________________________
Joshua Kim
Ridge IT Corporation
www.ridgeit.com<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.ridgeit.com%2F&data=02%7C01%7CJosh.Essert%40tradition.bank%7C315082acefd24bd8bc6808d828d3425f%7C911f77c51b1b4a36aa99d97497b47ffe%7C0%7C0%7C637304235924191219&sdata=UM8VfphbHuumohRiE2d5eQkUKAOwm3Jrgk3uPlHvShU%3D&reserved=0>

For support and licensing requests please send contact ***@***.******@***.***> for immediate assistance.

***@***.***

**Comment by jkim-ridgit** [comment]
To clarify, the chmod +x was on the logshipper.py file. You may want to adjust the .service to point to .py by default as the logshipper file is no longer there in the main branch.

Thank you,
Joshua
_________________________________
Joshua Kim
Ridge IT Corporation
www.ridgeit.com<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.ridgeit.com%2F&data=02%7C01%7CJosh.Essert%40tradition.bank%7C315082acefd24bd8bc6808d828d3425f%7C911f77c51b1b4a36aa99d97497b47ffe%7C0%7C0%7C637304235924191219&sdata=UM8VfphbHuumohRiE2d5eQkUKAOwm3Jrgk3uPlHvShU%3D&reserved=0>

For support and licensing requests please send contact ***@***.******@***.***> for immediate assistance.

***@***.***

From: Joshua Kim
Sent: Friday, April 15, 2022 10:20 AM
To: CrowdStrike/HEC-Log-Shipper ***@***.***>; CrowdStrike/HEC-Log-Shipper ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [CrowdStrike/HEC-Log-Shipper] status=203/EXEC (Issue #7)

Oh shoot, I forgot to update the issue. It worked when I added a shebang at the top to use python3 and chmod +x the file. Not sure if there’s a prettier way to do it, but I was running Centos 7.9.

Thank you,
Joshua
_________________________________
Joshua Kim
Ridge IT Corporation
www.ridgeit.com<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.ridgeit.com%2F&data=02%7C01%7CJosh.Essert%40tradition.bank%7C315082acefd24bd8bc6808d828d3425f%7C911f77c51b1b4a36aa99d97497b47ffe%7C0%7C0%7C637304235924191219&sdata=UM8VfphbHuumohRiE2d5eQkUKAOwm3Jrgk3uPlHvShU%3D&reserved=0>

For support and licensing requests please send contact ***@***.******@***.***> for immediate assistance.

***@***.***

**Comment by jshcodes** [comment]
Previous update missed this.  We'll get this updated.  Thank you for reporting it!  😄

**Comment by jkim-ridgit** [comment]
No problem, once I got it going, it works beautifully. Now if I can just figure out how to get host details into Humio from Crowdstrike, my boss will stop losing sleep. :D

Thank you,
Joshua
_________________________________
Joshua Kim
Ridge IT Corporation
www.ridgeit.com<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.ridgeit.com%2F&data=02%7C01%7CJosh.Essert%40tradition.bank%7C315082acefd24bd8bc6808d828d3425f%7C911f77c51b1b4a36aa99d97497b47ffe%7C0%7C0%7C637304235924191219&sdata=UM8VfphbHuumohRiE2d5eQkUKAOwm3Jrgk3uPlHvShU%3D&reserved=0>

For support and licensing requests please send contact ***@***.******@***.***> for immediate assistance.

***@***.***
